In [ ]:
# Mengimpor pustaka yang diperlukan
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, f1_score
from google.colab import drive



In [ ]:
# Memuat dataset Social Network Ads
drive.mount('/content/drive')
# Tentukan path file di dalam folder Colab Notebooks
file_path = '/content/drive/My Drive/Colab Notebooks/Social_Network_Ads.csv'
dataset = pd.read_csv(file_path)
# Melihat 5 baris pertama dari dataset
print(dataset.head())

# Dataset ini biasanya terdiri dari kolom: Age, EstimatedSalary, Purchased


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0


In [ ]:
# Mengambil kolom fitur (Age, EstimatedSalary) dan label (Purchased)
X = dataset.iloc[:, [0, 1]].values
y = dataset.iloc[:, 2].values


In [ ]:
# Membagi dataset menjadi data latih dan data uji (80% : 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


In [ ]:
# Melakukan standarisasi fitur agar memiliki skala yang serupa
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
# Membuat model SVM dengan kernel linear
linear_model = SVC(kernel='linear', random_state=0)
linear_model.fit(X_train, y_train)

# Melakukan prediksi
y_pred_linear = linear_model.predict(X_test)

# Menghitung confusion matrix dan F1 Score
cm_linear = confusion_matrix(y_test, y_pred_linear)
f1_linear = f1_score(y_test, y_pred_linear)

# Menampilkan hasil
print("Confusion Matrix (Linear Kernel):\n", cm_linear)
print("F1 Score (Linear Kernel):", f1_linear)


Confusion Matrix (Linear Kernel):
 [[57  1]
 [ 6 16]]
F1 Score (Linear Kernel): 0.8205128205128205


In [ ]:
# Membuat model SVM dengan kernel polynomial
poly_model = SVC(kernel='poly', random_state=0)
poly_model.fit(X_train, y_train)

# Melakukan prediksi
y_pred_poly = poly_model.predict(X_test)

# Menghitung confusion matrix dan F1 Score
cm_poly = confusion_matrix(y_test, y_pred_poly)
f1_poly = f1_score(y_test, y_pred_poly)

# Menampilkan hasil
print("Confusion Matrix (Polynomial Kernel):\n", cm_poly)
print("F1 Score (Polynomial Kernel):", f1_poly)


Confusion Matrix (Polynomial Kernel):
 [[58  0]
 [ 7 15]]
F1 Score (Polynomial Kernel): 0.8108108108108109


In [ ]:
# Membuat model SVM dengan kernel sigmoid
sigmoid_model = SVC(kernel='sigmoid', random_state=0)
sigmoid_model.fit(X_train, y_train)

# Melakukan prediksi
y_pred_sigmoid = sigmoid_model.predict(X_test)

# Menghitung confusion matrix dan F1 Score
cm_sigmoid = confusion_matrix(y_test, y_pred_sigmoid)
f1_sigmoid = f1_score(y_test, y_pred_sigmoid)

# Menampilkan hasil
print("Confusion Matrix (Sigmoid Kernel):\n", cm_sigmoid)
print("F1 Score (Sigmoid Kernel):", f1_sigmoid)


Confusion Matrix (Sigmoid Kernel):
 [[50  8]
 [ 8 14]]
F1 Score (Sigmoid Kernel): 0.6363636363636364


In [ ]:
# Membuat model SVM dengan kernel rbf (default kernel)
rbf_model = SVC(kernel='rbf', random_state=0)
rbf_model.fit(X_train, y_train)

# Melakukan prediksi
y_pred_rbf = rbf_model.predict(X_test)

# Menghitung confusion matrix dan F1 Score
cm_rbf = confusion_matrix(y_test, y_pred_rbf)
f1_rbf = f1_score(y_test, y_pred_rbf)

# Menampilkan hasil
print("Confusion Matrix (RBF Kernel):\n", cm_rbf)
print("F1 Score (RBF Kernel):", f1_rbf)


Confusion Matrix (RBF Kernel):
 [[55  3]
 [ 1 21]]
F1 Score (RBF Kernel): 0.9130434782608695


In [ ]:
# Membuat DataFrame untuk membandingkan hasil setiap kernel
results = pd.DataFrame({
    'Kernel': ['Linear', 'Polynomial', 'Sigmoid', 'RBF'],
    'F1 Score': [f1_linear, f1_poly, f1_sigmoid, f1_rbf]
})

# Menampilkan hasil perbandingan
print(results.sort_values(by='F1 Score', ascending=False))


       Kernel  F1 Score
3         RBF  0.913043
0      Linear  0.820513
1  Polynomial  0.810811
2     Sigmoid  0.636364
